---
- name: Install Postgres Server
  hosts: bbdd
  tasks:
   - name: Install packages
     yum: name={{ item }}
          state=installed
     with_items:
      - python-psycopg2
      - postgresql-server
      - postgresql
  
   - name: Initiate database
     command: service postgresql initdb
              creates=/var/lib/pgsql/data/postgresql.conf


   - name: Start PostgreSQL and enable at boot
     service: name=postgresql
              enabled=yes
              state=started
  

   - name: Add postgres user
     action: user name=postgres password=redhat

   - name: Ensure database is created
     postgresql_db: name=redmine
                 encoding='UTF-8'
                 lc_collate='en_US.UTF-8'
                 lc_ctype='en_US.UTF-8'
                 template='template0'
                 state=present
     become: true
     become_user: postgres

   - name: Ensure user has access to the database
     postgresql_user: db=redmine
                   name=redmine
                   password=redhat
                   priv=ALL
                   state=present
     become: true
     become_user: postgres

   - name: Ensure user does not have unnecessary privileges
     postgresql_user: name=redmine
                   role_attr_flags=NOSUPERUSER,NOCREATEDB
                   state=present
     become: true
     become_user: postgres

